//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSS_Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSS_Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill in All Required Fields..
        /// </summary>
        public static string BrandingErrorMessage {
            get {
                return ResourceManager.GetString("BrandingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branding Updated Succesfully..
        /// </summary>
        public static string BrandingUpdateSuccess {
            get {
                return ResourceManager.GetString("BrandingUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry the date selected is fully booked. Please select another day..
        /// </summary>
        public static string ConsultationFullyBookedMessage {
            get {
                return ResourceManager.GetString("ConsultationFullyBookedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Consultation Failed..
        /// </summary>
        public static string CreateConsultationFail {
            get {
                return ResourceManager.GetString("CreateConsultationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation Successfully Created..
        /// </summary>
        public static string CreateConsultationSuccess {
            get {
                return ResourceManager.GetString("CreateConsultationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Created Successfully..
        /// </summary>
        public static string CreateStudent_SuccessfulMessage {
            get {
                return ResourceManager.GetString("CreateStudent_SuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled Consultation Successfully..
        /// </summary>
        public static string DeleteConsultationSuccess {
            get {
                return ResourceManager.GetString("DeleteConsultationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICON (.ico)|*.ico|All Files (*.*)|*.*.
        /// </summary>
        public static string IconFileTypesRegexOpenDialog {
            get {
                return ResourceManager.GetString("IconFileTypesRegexOpenDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG (.jpg)|*.jpg|BITMAP (.bmp)|*.bmp|PNG (.png)|*.png|All Files (*.*)|*.*.
        /// </summary>
        public static string ImageFileTypesRegexOpenDialog {
            get {
                return ResourceManager.GetString("ImageFileTypesRegexOpenDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Login Details. Please try again..
        /// </summary>
        public static string IncorrectLoginDetailsMessage {
            get {
                return ResourceManager.GetString("IncorrectLoginDetailsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Created Successfully. Please Login With Your New Password..
        /// </summary>
        public static string Login_CheckPassword_Password_Created_Successfully {
            get {
                return ResourceManager.GetString("Login_CheckPassword_Password_Created_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Password..
        /// </summary>
        public static string Login_CheckPassword_Please_Enter_a_Password_ {
            get {
                return ResourceManager.GetString("Login_CheckPassword_Please_Enter_a_Password_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Insert Correct Password.
        /// </summary>
        public static string PassWordCreateDoNotMatchError {
            get {
                return ResourceManager.GetString("PassWordCreateDoNotMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Update Successful..
        /// </summary>
        public static string Profile_Update_Successful {
            get {
                return ResourceManager.GetString("Profile_Update_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Information.
        /// </summary>
        public static string SearchStudentMessageBoxHeading {
            get {
                return ResourceManager.GetString("SearchStudentMessageBoxHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutor Information.
        /// </summary>
        public static string SearchTutorInformationHeading {
            get {
                return ResourceManager.GetString("SearchTutorInformationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutor Information.
        /// </summary>
        public static string SearchTutorModal_displayStudentInformation_Tutor_Information {
            get {
                return ResourceManager.GetString("SearchTutorModal_displayStudentInformation_Tutor_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sent To New Student..
        /// </summary>
        public static string SendEmailSuccessfulMessage {
            get {
                return ResourceManager.GetString("SendEmailSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Consultation Successfully..
        /// </summary>
        public static string UpdateConsultationSuccess {
            get {
                return ResourceManager.GetString("UpdateConsultationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to Group Successfully..
        /// </summary>
        public static string UpdateGroupSuccess {
            get {
                return ResourceManager.GetString("UpdateGroupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Updated Successfully..
        /// </summary>
        public static string UpdateStudentAttendanceSuccess {
            get {
                return ResourceManager.GetString("UpdateStudentAttendanceSuccess", resourceCulture);
            }
        }
    }
}
