-- Create BRANDING
USE IS2G10_DBSSS;
GO
CREATE TABLE TUTOR_AVAILABLE_TIMES (
	tutor_time_id int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	tutor_id int NOT NULL FOREIGN KEY REFERENCES dbo.TUTOR(tutor_id),
	available_day NVARCHAR(255),
	available_time TIME,
	date_free DATETIME
);
GO
PRINT ('TUTOR_AVAILABLE_TIMES CREATED');

DROP TABLE TUTOR_AVAILABLE_TIMES;