-- Create BRANDING
USE IS2G10_DBSSS;
GO
CREATE TABLE USER_ROLE (
	user_roles_id int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	user_role nvarchar(255),
);
GO
PRINT ('USER_ROLE CREATED');

INSERT INTO USER_ROLE VALUES ('Administrator');
INSERT INTO USER_ROLE VALUES ('Coordinator');
INSERT INTO USER_ROLE VALUES ('Tutor');
INSERT INTO USER_ROLE VALUES ('Student');

DROP TABLE USER_ROLE;